### ISSUE TITLE
Failed to load Scrollback :-( Tap to retry

### ISSUE THREAD

**Issue by metao1** [scrollback/android-wrapper#12]
Hi,
I cloned the project from this repository.I opened it as a Gradle project installed it on my phone,it successfully installed,but when the program tries to load this massage appears "Failed to load Scrollback :-( Tap to retry". Would you please guild me to successfully install this program and debug it?
Thanks
Metao

**Comment by karthikb351** [comment]
Could you open up adb logs and give us the stacktrace? That would be super useful.

**Comment by metao1** [comment]
Here it is:
09-14 00:08:18.732  26110-26110/io.scrollback.app.development I/art﹕ Late-enabling -Xcheck:jni
09-14 00:08:18.963  26110-26110/io.scrollback.app.development I/WebViewFactory﹕ Loading com.google.android.webview version 42.0.2311.138 (code 2311138)
09-14 00:08:18.978  26110-26110/io.scrollback.app.development I/LibraryLoader﹕ Time to load native libraries: 3 ms (timestamps 2279-2282)
09-14 00:08:18.978  26110-26110/io.scrollback.app.development I/LibraryLoader﹕ Expected native library version number "",actual native library version number ""
09-14 00:08:18.995  26110-26110/io.scrollback.app.development V/WebViewChromiumFactoryProvider﹕ Binding Chromium to main looper Looper (main, tid 1) {2cb1ef51}
09-14 00:08:18.995  26110-26110/io.scrollback.app.development I/LibraryLoader﹕ Expected native library version number "",actual native library version number ""
09-14 00:08:18.995  26110-26110/io.scrollback.app.development I/chromium﹕ [INFO:library_loader_hooks.cc(112)] Chromium logging enabled: level = 0, default verbosity = 0
09-14 00:08:19.008  26110-26110/io.scrollback.app.development I/BrowserStartupController﹕ Initializing chromium process, singleProcess=true
09-14 00:08:19.009  26110-26110/io.scrollback.app.development W/art﹕ Attempt to remove local handle scope entry from IRT, ignoring
09-14 00:08:19.010  26110-26110/io.scrollback.app.development E/SysUtils﹕ ApplicationContext is null in ApplicationStatus
09-14 00:08:19.030  26110-26138/io.scrollback.app.development W/AudioManagerAndroid﹕ Requires BLUETOOTH permission
09-14 00:08:19.043  26110-26110/io.scrollback.app.development W/chromium﹕ [WARNING:resource_bundle.cc(286)] locale_file_path.empty()
09-14 00:08:19.044  26110-26110/io.scrollback.app.development I/chromium﹕ [INFO:aw_browser_main_parts.cc(63)] Load from apk succesful, fd=35 off=50376 len=3345
09-14 00:08:19.045  26110-26110/io.scrollback.app.development I/chromium﹕ [INFO:aw_browser_main_parts.cc(76)] Loading webviewchromium.pak from, fd:36 off:7953032 len:1161174
09-14 00:08:19.058  26110-26110/io.scrollback.app.development I/Adreno-EGL﹕ <qeglDrvAPI_eglInitialize:379>: QUALCOMM Build: 01/15/15, ab0075f, Id3510ff6dc
09-14 00:08:19.170  26110-26144/io.scrollback.app.development W/chromium﹕ [WARNING:data_reduction_proxy_config.cc(150)] SPDY proxy OFF at startup
09-14 00:08:19.185  26110-26110/io.scrollback.app.development W/art﹕ Attempt to remove local handle scope entry from IRT, ignoring
09-14 00:08:19.195  26110-26110/io.scrollback.app.development W/AwContents﹕ onDetachedFromWindow called when already detached. Ignoring
09-14 00:08:19.209  26110-26110/io.scrollback.app.development D/scrollback-android-sdk﹕ Registration not found.
09-14 00:08:19.215  26110-26110/io.scrollback.app.development W/art﹕ Attempt to remove local handle scope entry from IRT, ignoring
09-14 00:08:19.215  26110-26110/io.scrollback.app.development W/art﹕ Attempt to remove local handle scope entry from IRT, ignoring
09-14 00:08:19.274  26110-26164/io.scrollback.app.development D/OpenGLRenderer﹕ Use EGL_SWAP_BEHAVIOR_PRESERVED: true
09-14 00:08:19.284  26110-26110/io.scrollback.app.development D/Atlas﹕ Validating map...
09-14 00:08:19.349  26110-26164/io.scrollback.app.development I/OpenGLRenderer﹕ Initialized EGL, version 1.4
09-14 00:08:19.356  26110-26164/io.scrollback.app.development D/OpenGLRenderer﹕ Enabling debug mode 0
09-14 00:08:19.463  26110-26110/io.scrollback.app.development W/IInputConnectionWrapper﹕ showStatusIcon on inactive InputConnection
09-14 00:08:19.474  26110-26110/io.scrollback.app.development W/BindingManager﹕ Cannot call determinedVisibility() - never saw a connection for the pid: 26110
09-14 00:08:19.475  26110-26110/io.scrollback.app.development W/BindingManager﹕ Cannot call determinedVisibility() - never saw a connection for the pid: 26110
09-14 00:08:19.499  26110-26110/io.scrollback.app.development I/chromium﹕ [INFO:CONSOLE(0)] "Not allowed to load local resource: file:///android_asset/webkit/android-weberror.png", source: data:text/html,chromewebdata (0)
09-14 00:11:58.097  26110-26120/io.scrollback.app.development I/art﹕ Debugger is no longer active
09-14 00:30:40.986  26110-26110/io.scrollback.app.development W/IInputConnectionWrapper﹕ showStatusIcon on inactive InputConnection

**Comment by satya164** [comment]
@metao1 Change your build flavour to stage/production

**Comment by metao1** [comment]
Thanks it works!
